on: [pull_request]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Get specified version
        id: version
        run: |
          VERSION=`cat pubspec.yml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`
          echo "::set-output name=version::$(echo $VERSION)"
        shell: bash
      - name: Get the version
        run: echo "${{ steps.version.outputs.version }} published"
